"""add profile fields to user

Revision ID: 50d09a03c459
Revises: 08c1823e78c8
Create Date: 2026-08-30 18:36:04.720149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) in autogenerated ops


# revision identifiers, used by Alembic.
revision: str = '50d09a03c459'
down_revision: Union[str, Sequence[str], None] = '08c1823e78c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('animal_asset_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('avatar_color', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('bio_line_1', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('bio_line_2', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.alter_column('user', 'external_auth_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_owner_user_id'), 'user', ['owner_user_id'], unique=False)
    op.create_foreign_key('fk_user_owner_user_id_user', 'user', 'user', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_owner_user_id_user', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_owner_user_id'), table_name='user')
    op.alter_column('user', 'external_auth_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'owner_user_id')
    op.drop_column('user', 'bio_line_2')
    op.drop_column('user', 'bio_line_1')
    op.drop_column('user', 'avatar_color')
    op.drop_column('user', 'animal_asset_name')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
