"""add avatar_mode to user

Revision ID: 77fa0956ea17
Revises: 50d09a03c459
Create Date: 2026-09-06 23:06:37.140814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) in autogenerated ops


# revision identifiers, used by Alembic.
revision: str = '77fa0956ea17'
down_revision: Union[str, Sequence[str], None] = '50d09a03c459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'avatar_mode',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='animal',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_mode')
    # ### end Alembic commands ###
